### PR TITLE
Add other and both traversal steps

### PR DESCRIPTION
**Pull request by bertdemiranda**
I have added both(_e) and other(_v) traversals. Also to __ I have added the in_ and in_e traversals.

The tests in integration_traversal.rs run without errors, but I don't know how to get the tests in integration_traversal_v2.rs running.

Regards,
Bert de Miranda.

### CODE REVIEW

**Comment by wolf4ood** [comment]
Hi @bertdemiranda 

thanks for the PR, It looks great. could run `cargo fmt` and push the the format fix? Seems that the build is failing for that

https://travis-ci.org/github/wolf4ood/gremlin-rs/jobs/710718589

Thanks :)

**Comment by bertdemiranda** [comment]
Hallo Enrico,

I ran cargo fmt, which made the modifications as indicated.

Ran some of the tests with results shown in the attached log.

All of the traversal_v2 tests fail on my system somehow. Maybe I need to
configure something?

Regards,

**Comment by wolf4ood** [comment]
Hi @bertdemiranda 

do you have an example of failing?

Seems to be working on the CI https://travis-ci.org/github/wolf4ood/gremlin-rs
Works on my machine also. Send me some logs when you can i will check it.

Meanwhile i'm going to merge this

Thanks :)

**Comment by bertdemiranda** [comment]
This log file shows the tests I ran:

[Test log](https://github.com/wolf4ood/gremlin-rs/files/4970847/Test.log)

Regards,

**Comment by bertdemiranda** [comment]
Enrico,

I did a fresh clone of wolf4ood/gremlin-rs and ran cargo build and some 
tests.

Attached you find the log file.

Regards,


bert@bert-SH87R:~/Research$ git clone https://github.com/wolf4ood/gremlin-rs.git
Cloning into 'gremlin-rs'...
remote: Enumerating objects: 282, done.
remote: Counting objects: 100% (282/282), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 3727 (delta 175), reused 170 (delta 98), pack-reused 3445
Receiving objects: 100% (3727/3727), 1.13 MiB | 537.00 KiB/s, done.
Resolving deltas: 100% (2650/2650), done.
bert@bert-SH87R:~/Research$ cd gremlin-rs/
bert@bert-SH87R:~/Research/gremlin-rs$ ls
Cargo.toml          docker-compose  gremlin-derive    LICENSE.md
CODE_OF_CONDUCT.md  gremlin-client  gremlin-tutorial  README.md
bert@bert-SH87R:~/Research/gremlin-rs$ cd gremlin-client/
bert@bert-SH87R:~/Research/gremlin-rs/gremlin-client$ cargo build
    Updating crates.io index
  Downloaded proc-macro2 v1.0.19
  Downloaded syn v1.0.35
  Downloaded log v0.4.11
  Downloaded libc v0.2.73
  Downloaded 4 crates (779.8 KB) in 0.64s
   Compiling libc v0.2.73
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling autocfg v0.1.7
   Compiling rand_core v0.4.2
   Compiling proc-macro2 v1.0.19
   Compiling cc v1.0.58
   Compiling pkg-config v0.3.18
   Compiling unicode-xid v0.2.1
   Compiling log v0.4.11
   Compiling syn v1.0.35
   Compiling byteorder v1.3.4
   Compiling bitflags v1.2.1
   Compiling getrandom v0.1.14
   Compiling version_check v0.1.5
   Compiling openssl v0.10.30
   Compiling matches v0.1.8
   Compiling foreign-types-shared v0.1.1
   Compiling serde_derive v1.0.114
   Compiling tinyvec v0.3.3
   Compiling instant v0.1.6
   Compiling smallvec v1.4.1
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.114
   Compiling native-tls v0.2.4
   Compiling httparse v1.3.4
   Compiling lazy_static v1.4.0
   Compiling percent-encoding v1.0.1
   Compiling openssl-probe v0.1.2
   Compiling safemem v0.3.3
   Compiling ppv-lite86 v0.2.8
   Compiling ryu v1.0.5
   Compiling sha1 v0.6.0
   Compiling typeable v0.1.2
   Compiling language-tags v0.2.2
   Compiling traitobject v0.1.0
   Compiling serde_json v1.0.56
   Compiling itoa v0.4.6
   Compiling base64 v0.12.3
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling unicode-bidi v0.3.4
   Compiling foreign-types v0.3.2
   Compiling lock_api v0.4.1
   Compiling unicode-normalization v0.1.13
   Compiling unicase v1.4.2
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling openssl-sys v0.9.58
   Compiling log v0.3.9
   Compiling quote v1.0.7
   Compiling base64 v0.10.1
   Compiling base64 v0.9.3
   Compiling idna v0.1.5
   Compiling mime v0.2.6
   Compiling rand_os v0.1.3
   Compiling parking_lot_core v0.8.0
   Compiling time v0.1.43
   Compiling num_cpus v1.13.0
   Compiling rand_core v0.5.1
   Compiling url v1.7.2
   Compiling parking_lot v0.11.0
   Compiling rand_chacha v0.2.2
   Compiling scheduled-thread-pool v0.2.5
   Compiling r2d2 v0.8.9
   Compiling rand v0.7.3
   Compiling chrono v0.4.13
   Compiling hyper v0.10.16
   Compiling thiserror-impl v1.0.20
   Compiling websocket-base v0.24.0
   Compiling websocket v0.24.0
   Compiling thiserror v1.0.20
   Compiling uuid v0.8.1
   Compiling gremlin-client v0.6.0 (/media/bert/Data/Research/gremlin-rs/gremlin-client)
    Finished dev [unoptimized + debuginfo] target(s) in 36.18s
bert@bert-SH87R:~/Research/gremlin-rs/gremlin-client$ cargo test
   Compiling gremlin-client v0.6.0 (/media/bert/Data/Research/gremlin-rs/gremlin-client)
    Finished test [unoptimized + debuginfo] target(s) in 10.60s
     Running /media/bert/Data/Research/gremlin-rs/target/debug/deps/gremlin_client-1050d94571e905d0

running 57 tests
test io::serializer_v1::tests::test_number_input ... ok
test connection::tests::connection_option_build_url ... ok
test io::serializer_v1::tests::test_collections ... ok
test io::serializer_v2::tests::test_edge ... ok
test io::serializer_v2::tests::test_map_with_token ... ok
test io::serializer_v2::tests::test_number_input ... ok
test io::serializer_v2::tests::test_collections ... ok
test io::serializer_v2::tests::test_token ... ok
test io::serializer_v2::tests::test_properties ... ok
test io::serializer_v3::tests::test_collections ... ok
test io::serializer_v2::tests::test_path ... ok
test io::serializer_v3::tests::test_properties ... ok
test io::serializer_v3::tests::test_number_input ... ok
test io::serializer_v3::tests::test_map_with_token ... ok
test io::serializer_v3::tests::test_edge ... ok
test io::serializer_v3::tests::test_token ... ok
test io::serializer_v2::tests::test_vertex ... ok
test io::serializer_v3::tests::test_path ... ok
test process::traversal::graph_traversal_source::tests::add_e_test ... ok
test process::traversal::graph_traversal_source::tests::add_e_test_with_traversal ... ok
test io::serializer_v3::tests::test_vertex ... ok
test process::traversal::graph_traversal_source::tests::add_v_with_property_test ... ok
test process::traversal::graph_traversal_source::tests::add_v_test ... ok
test process::traversal::graph_traversal_source::tests::count_test ... ok
test process::traversal::graph_traversal_source::tests::coalesce_test ... ok
test process::traversal::graph_traversal_source::tests::dedup_test ... ok
test process::traversal::graph_traversal_source::tests::e_traversal ... ok
test process::traversal::graph_traversal_source::tests::drop_test ... ok
test process::traversal::graph_traversal_source::tests::fold_test ... ok
test connection::tests::it_should_connect ... ok
test process::traversal::graph_traversal_source::tests::as_test ... ok
test process::traversal::graph_traversal_source::tests::group_count_test ... ok
test process::traversal::graph_traversal_source::tests::group_count_by_test ... ok
test process::traversal::graph_traversal_source::tests::label_step_test ... ok
test process::traversal::graph_traversal_source::tests::group_by_test ... ok
test process::traversal::graph_traversal_source::tests::limit_test ... ok
test process::traversal::graph_traversal_source::tests::not_test ... ok
test io::serializer_v3::tests::test_traversal_metrics ... ok
test process::traversal::graph_traversal_source::tests::match_test ... ok
test process::traversal::graph_traversal_source::tests::path_test ... ok
test process::traversal::graph_traversal_source::tests::or_test ... ok
test process::traversal::graph_traversal_source::tests::order_test ... ok
test process::traversal::graph_traversal_source::tests::numerical_test ... ok
test process::traversal::graph_traversal_source::tests::unfold_test ... ok
test process::traversal::graph_traversal_source::tests::v_has_traversal ... ok
test process::traversal::graph_traversal_source::tests::v_has_label_traversal ... ok
test process::traversal::graph_traversal_source::tests::properties_step_test ... ok
test process::traversal::graph_traversal_source::tests::select_test ... ok
test process::traversal::graph_traversal_source::tests::property_map_step_test ... ok
test structure::macros::test::vertex_macro_with_properties ... ok
test process::traversal::graph_traversal_source::tests::value_map_step_test ... ok
test process::traversal::graph_traversal_source::tests::v_traversal ... ok
test structure::macros::test::vertex_macro ... ok
test process::traversal::graph_traversal_source::tests::values_step_test ... ok
test process::traversal::graph_traversal_source::tests::where_test ... ok
test process::traversal::graph_traversal_source::tests::v_has_traversal_with_p ... ok
test pool::tests::it_should_create_a_connection_pool ... ok

test result: ok. 57 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /media/bert/Data/Research/gremlin-rs/target/debug/deps/common-5951ec9a1b29ccb7

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /media/bert/Data/Research/gremlin-rs/target/debug/deps/integration_client-d32303a40232acb3

running 15 tests
test test_edge_query ... FAILED
test test_edge_creation ... ok
test test_client_connection_ok ... ok
test test_empty_query ... ok
test test_complex_vertex_creation_with_properties ... ok
test test_explain ... ok
test test_group_count_vertex ... ok
test test_group_count_edge ... ok
test test_vertex_creation ... ok
test test_profile ... ok
test test_wrong_alias ... ok
test test_vertex_query ... FAILED
test test_wrong_query ... ok
test test_ko_credentials ... FAILED
test test_ok_credentials ... FAILED

failures:

---- test_edge_query stdout ----
thread 'test_edge_query' panicked at 'index out of bounds: the len is 0 but the index is 0', gremlin-client/tests/integration_client.rs:125:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_vertex_query stdout ----
thread 'test_vertex_query' panicked at 'index out of bounds: the len is 0 but the index is 0', gremlin-client/tests/integration_client.rs:112:26

---- test_ko_credentials stdout ----
thread 'test_ko_credentials' panicked at 'Cannot connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/integration_client.rs:60:6

---- test_ok_credentials stdout ----
thread 'test_ok_credentials' panicked at 'Cannot connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/integration_client.rs:41:6


failures:
    test_edge_query
    test_ko_credentials
    test_ok_credentials
    test_vertex_query

test result: FAILED. 11 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test integration_client'
bert@bert-SH87R:~/Research/gremlin-rs/gremlin-client$ cargo test --test integration_traversal
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running /media/bert/Data/Research/gremlin-rs/target/debug/deps/integration_traversal-f1a6d5a5169ac6d6

running 48 tests
test test_add_v ... ok
test iter_terminator_test ... ok
test not_step_test ... ok
test test_add_e ... FAILED
test or_step_test ... ok
test drop_step_test ... ok
test order_step_test ... ok
test match_step_test ... ok
test test_add_v_with_properties ... ok
test test_add_v_with_property_many ... ok
test test_count ... ok
test test_coalesce ... ok
test test_choose ... ok
test test_fold_step ... ok
test test_group_count_step ... ok
test test_has_many ... ok
test test_coalesce_unfold ... ok
test test_group_by_step ... ok
test test_dedup_step ... ok
test test_has_with_p_steps ... ok
test test_has_with_text_p_step ... ok
test test_path_step ... ok
test test_numerical_steps ... ok
test test_label_step ... ok
test test_limit_step ... ok
test test_properties_step ... ok
test test_property_map ... ok
test test_local ... ok
test test_property_cardinality ... ok
test test_simple_edge_traversal ... ok
test test_select_step ... ok
test test_repeat_until_loops_loops ... ok
test test_simple_edge_traversal_id ... ok
test test_simple_edge_traversal_with_label ... ok
test test_select_pop ... ok
test test_simple_vertex_traversal_with_label ... ok
test test_sample ... ok
test test_simple_path ... ok
test test_simple_vertex_traversal ... ok
test test_simple_vertex_traversal_with_id ... ok
test test_unfold_step ... ok
test test_uwnrap_map ... ok
test test_simple_vertex_traversal_with_label_and_has ... ok
test where_step_test ... ok
test test_value_map ... ok
test test_simple_vertex_traversal_with_multiple_id ... ok
test test_values ... ok
test test_traversal ... ok

failures:

---- test_add_e stdout ----
thread 'test_add_e' panicked at 'index out of bounds: the len is 0 but the index is 0', gremlin-client/tests/integration_traversal.rs:535:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_add_e

test result: FAILED. 47 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test integration_traversal'
bert@bert-SH87R:~/Research/gremlin-rs/gremlin-client$ cargo test --test integration_traversal_v2    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running /media/bert/Data/Research/gremlin-rs/target/debug/deps/integration_traversal_v2-6e7f57d68e5ad1e8

running 45 tests
test match_step_test_v2 ... FAILED
test not_step_test_v2 ... FAILED
test order_step_test_v2 ... FAILED
test drop_step_test_v2 ... FAILED
test iter_terminator_test_v2 ... FAILED
test test_add_v_v2 ... FAILED
test test_add_e_v2 ... FAILED
test or_step_test_v2 ... FAILED
test test_add_v_with_properties_v2 ... FAILED
test test_count_v2 ... FAILED
test test_add_v_with_property_many_v2 ... FAILED
test test_dedup_step_v2 ... FAILED
test test_group_by_step_v2 ... FAILED
test test_group_count_step_v2 ... FAILED
test test_fold_step_v2 ... FAILED
test test_has_many_v2 ... FAILED
test test_has_with_p_steps_v2 ... FAILED
test test_label_step_v2 ... FAILED
test test_has_with_text_p_step_v2 ... FAILED
test test_limit_step_v2 ... FAILED
test test_numerical_steps_v2 ... FAILED
test test_local_v2 ... FAILED
test test_path_step_v2 ... FAILED
test test_properties_step_v2 ... FAILED
test test_property_cardinality_v2 ... FAILED
test test_property_map_v2 ... FAILED
test test_repeat_until_loops_loops_v2 ... FAILED
test test_sample_v2 ... FAILED
test test_select_step_v2 ... FAILED
test test_select_pop_v2 ... FAILED
test test_simple_edge_traversal_id_v2 ... FAILED
test test_simple_edge_traversal_v2 ... FAILED
test test_simple_edge_traversal_with_label_v2 ... FAILED
test test_simple_vertex_traversal_v2 ... FAILED
test test_simple_path_v2 ... FAILED
test test_simple_vertex_traversal_with_id_v2 ... FAILED
test test_simple_vertex_traversal_with_label_v2 ... FAILED
test test_simple_vertex_traversal_with_label_and_has_v2 ... FAILED
test test_simple_vertex_traversal_with_multiple_id_v2 ... FAILED
test test_traversal_v2 ... FAILED
test test_unfold_step_v2 ... FAILED
test test_uwnrap_map_v2 ... FAILED
test test_value_map_v2 ... FAILED
test test_values_v2 ... FAILED
test where_step_test_v2 ... FAILED

failures:

---- match_step_test_v2 stdout ----
thread 'match_step_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- not_step_test_v2 stdout ----
thread 'not_step_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- order_step_test_v2 stdout ----
thread 'order_step_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- drop_step_test_v2 stdout ----
thread 'drop_step_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- iter_terminator_test_v2 stdout ----
thread 'iter_terminator_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_add_v_v2 stdout ----
thread 'test_add_v_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_add_e_v2 stdout ----
thread 'test_add_e_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- or_step_test_v2 stdout ----
thread 'or_step_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_add_v_with_properties_v2 stdout ----
thread 'test_add_v_with_properties_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_count_v2 stdout ----
thread 'test_count_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_add_v_with_property_many_v2 stdout ----
thread 'test_add_v_with_property_many_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_dedup_step_v2 stdout ----
thread 'test_dedup_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_group_by_step_v2 stdout ----
thread 'test_group_by_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_group_count_step_v2 stdout ----
thread 'test_group_count_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_fold_step_v2 stdout ----
thread 'test_fold_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_has_many_v2 stdout ----
thread 'test_has_many_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_has_with_p_steps_v2 stdout ----
thread 'test_has_with_p_steps_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_label_step_v2 stdout ----
thread 'test_label_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_has_with_text_p_step_v2 stdout ----
thread 'test_has_with_text_p_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_limit_step_v2 stdout ----
thread 'test_limit_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_numerical_steps_v2 stdout ----
thread 'test_numerical_steps_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_local_v2 stdout ----
thread 'test_local_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_path_step_v2 stdout ----
thread 'test_path_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_properties_step_v2 stdout ----
thread 'test_properties_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_property_cardinality_v2 stdout ----
thread 'test_property_cardinality_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_property_map_v2 stdout ----
thread 'test_property_map_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_repeat_until_loops_loops_v2 stdout ----
thread 'test_repeat_until_loops_loops_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_sample_v2 stdout ----
thread 'test_sample_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_select_step_v2 stdout ----
thread 'test_select_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_select_pop_v2 stdout ----
thread 'test_select_pop_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_edge_traversal_id_v2 stdout ----
thread 'test_simple_edge_traversal_id_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_edge_traversal_v2 stdout ----
thread 'test_simple_edge_traversal_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_edge_traversal_with_label_v2 stdout ----
thread 'test_simple_edge_traversal_with_label_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_vertex_traversal_v2 stdout ----
thread 'test_simple_vertex_traversal_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_path_v2 stdout ----
thread 'test_simple_path_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_vertex_traversal_with_id_v2 stdout ----
thread 'test_simple_vertex_traversal_with_id_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_vertex_traversal_with_label_v2 stdout ----
thread 'test_simple_vertex_traversal_with_label_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_vertex_traversal_with_label_and_has_v2 stdout ----
thread 'test_simple_vertex_traversal_with_label_and_has_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_simple_vertex_traversal_with_multiple_id_v2 stdout ----
thread 'test_simple_vertex_traversal_with_multiple_id_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_traversal_v2 stdout ----
thread 'test_traversal_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_unfold_step_v2 stdout ----
thread 'test_unfold_step_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_uwnrap_map_v2 stdout ----
thread 'test_uwnrap_map_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_value_map_v2 stdout ----
thread 'test_value_map_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- test_values_v2 stdout ----
thread 'test_values_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40

---- where_step_test_v2 stdout ----
thread 'where_step_test_v2' panicked at 'It should connect: Pool(Error(Some("WebSocketError: I/O failure")))', gremlin-client/tests/common.rs:30:40


failures:
    drop_step_test_v2
    iter_terminator_test_v2
    match_step_test_v2
    not_step_test_v2
    or_step_test_v2
    order_step_test_v2
    test_add_e_v2
    test_add_v_v2
    test_add_v_with_properties_v2
    test_add_v_with_property_many_v2
    test_count_v2
    test_dedup_step_v2
    test_fold_step_v2
    test_group_by_step_v2
    test_group_count_step_v2
    test_has_many_v2
    test_has_with_p_steps_v2
    test_has_with_text_p_step_v2
    test_label_step_v2
    test_limit_step_v2
    test_local_v2
    test_numerical_steps_v2
    test_path_step_v2
    test_properties_step_v2
    test_property_cardinality_v2
    test_property_map_v2
    test_repeat_until_loops_loops_v2
    test_sample_v2
    test_select_pop_v2
    test_select_step_v2
    test_simple_edge_traversal_id_v2
    test_simple_edge_traversal_v2
    test_simple_edge_traversal_with_label_v2
    test_simple_path_v2
    test_simple_vertex_traversal_v2
    test_simple_vertex_traversal_with_id_v2
    test_simple_vertex_traversal_with_label_and_has_v2
    test_simple_vertex_traversal_with_label_v2
    test_simple_vertex_traversal_with_multiple_id_v2
    test_traversal_v2
    test_unfold_step_v2
    test_uwnrap_map_v2
    test_value_map_v2
    test_values_v2
    where_step_test_v2

test result: FAILED. 0 passed; 45 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test integration_traversal_v2'
bert@bert-SH87R:~/Research/gremlin-rs/gremlin-client$

**Pull request merged**
