### PR TITLE
Simplify features, strip dependencies and remove native-tls

### LINKED ISSUE #176: Native TLS as optional
Hey there !

I'm currently using gremlin-client in one of my project. Unfortunately, gremlin-client rely on `native-tls` which itself rely on dynamically link openssl.

This can bring errors during compilation (cross compilation) or runtime.

Is it possible to make this dependency optional and rely on rustls instead ?

I might have the time to do it, but I'd like to discuss the implementation with you first !
Please let me know what you think about this !

### PR DESCRIPTION
**Pull request by mlemesle**
Closes #176 and #180

### CODE REVIEW

**Comment by mlemesle** [comment]
Hello !

I've been working on these issues. This is still work in progress, but you can see where the developments are going.
Is that what you had in mind ?

Can you please have a look and tell me if I can continue on this path or if those changes are going the wrong way ?

Thanks :)

**Comment by mlemesle** [comment]
Hey @wolf4ood , thanks for replying !

What I had in mind is to be runtime agnostic. I thought that's what you had in mind as well when you mentioned async and sync features.

Unfortunately, I think this would require a major refactor of the whole connection and client parts.

What do you think?

**Comment by wolf4ood** [comment]
@mlemesle 

the idea was to have to set of feature

-async 
-sync 

with async by default

For the async it would be cool to have runtime agnostic but it's not easy and sometimes requires additional libraries.

We have a couple of options

Option 1

`async` as base feature like now and activate tokio or async-td

Option2

`async`

as the only async feature and we will drop `async-std`


The second one probably it''s more drastic but it will simplify a lot everything. And probably it will also work with async-std but we have to check that

**Comment by mlemesle** [comment]
I'll see what I can do.
Maybe I'll need to ask some questions later, but for now I need to process those informations.

Thanks for your help!

**Comment by mlemesle** [comment]
Closed in favor of #187

**Pull request closed without merging**
